#!/usr/bin/env python3
"""Ingest Eternal design-intelligence exports.

Validates signals/*.jsonl against the v0 schema (see README.md), refreshes
design-intelligence/digest.md, and emits training/tasks/eternal-design-tasks.jsonl
for batch trajectory generation. Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DI = ROOT / "design-intelligence"
SIGNALS_DIR = DI / "signals"
PRINCIPLES_DIR = DI / "principles"
DIGEST = DI / "digest.md"
TASKS_OUT = ROOT.parent / "training" / "tasks" / "eternal-design-tasks.jsonl"

REQUIRED = ("id", "type", "task", "summary")
TYPES = {"choice", "rating", "outcome"}

TASK_TEMPLATE = (
    "Design task derived from Eternal signal {id} ({task}): {summary} "
    "Produce a new design for this brief, applying the relevant principles from "
    "the Eternal corpus at $HERMES_HOME/eternal/design-intelligence/. Cite every "
    "principle that shapes a decision, run one self-critique pass, and deliver "
    "the final artifact as a file."
)


def load_signals() -> tuple[list[dict], list[str]]:
    signals: list[dict] = []
    errors: list[str] = []
    seen_ids: set[str] = set()
    for path in sorted(SIGNALS_DIR.glob("*.jsonl")):
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line.strip():
                continue
            where = f"{path.name}:{lineno}"
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                errors.append(f"{where}: invalid JSON ({e})")
                continue
            missing = [k for k in REQUIRED if not obj.get(k)]
            if missing:
                errors.append(f"{where}: missing required field(s) {missing}")
                continue
            if obj["type"] not in TYPES:
                errors.append(f"{where}: type {obj['type']!r} not in {sorted(TYPES)}")
                continue
            if obj["id"] in seen_ids:
                errors.append(f"{where}: duplicate id {obj['id']!r}")
                continue
            seen_ids.add(obj["id"])
            signals.append(obj)
    return signals, errors


def write_digest(signals: list[dict]) -> None:
    principles = sorted(p.stem for p in PRINCIPLES_DIR.glob("*.md"))
    by_type = Counter(s["type"] for s in signals)
    by_task = Counter(s["task"] for s in signals)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Eternal design-intelligence digest",
        "",
        f"_Generated by `eternal/ingest.py` — {now}. Do not edit by hand._",
        "",
        f"**{len(signals)} signals** — "
        + ", ".join(f"{n} {t}" for t, n in sorted(by_type.items())),
        "",
        "## Signals by task type",
        "",
    ]
    lines += [f"- **{task}**: {n}" for task, n in by_task.most_common()]
    lines += ["", "## Principles", ""]
    if principles:
        lines += [f"- `eternal:{slug}` → `principles/{slug}.md`" for slug in principles]
    else:
        lines.append("_None distilled yet — read raw signals directly._")
    lines += ["", "## Recent signals", ""]
    for s in signals[-15:]:
        lines.append(f"- `{s['id']}` ({s['type']}/{s['task']}): {s['summary']}")
    if not signals:
        lines.append("_No signals ingested yet._")
    DIGEST.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_tasks(signals: list[dict]) -> None:
    TASKS_OUT.parent.mkdir(parents=True, exist_ok=True)
    with TASKS_OUT.open("w", encoding="utf-8") as f:
        for s in signals:
            f.write(json.dumps({"prompt": TASK_TEMPLATE.format(**s)}) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate only")
    args = parser.parse_args()

    SIGNALS_DIR.mkdir(parents=True, exist_ok=True)
    PRINCIPLES_DIR.mkdir(parents=True, exist_ok=True)

    signals, errors = load_signals()
    for err in errors:
        print(f"ERROR {err}", file=sys.stderr)
    if args.check:
        print(f"{len(signals)} valid signals, {len(errors)} errors")
        return 1 if errors else 0

    write_digest(signals)
    write_tasks(signals)
    print(f"digest: {DIGEST.relative_to(ROOT.parent)} ({len(signals)} signals)")
    print(f"tasks:  {TASKS_OUT.relative_to(ROOT.parent)}")
    if errors:
        print(f"{len(errors)} bad lines skipped (see stderr)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
